const types = {
    
    REGISTER_USER : 'REGISTER_USER',
    RECEIVE_USER_LIST: 'RECEIVE_USER_LIST',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOGIN_USER: 'LOGIN_USER',
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    RECEIVE_DEPARTMENTS: 'RECEIVE_DEPARTMENTS',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    ADD_FILE: 'ADD_FILE',
    UPDATE_FILE: 'UPDATE_FILE',
    RECIEVE_FILES: 'RECEIVE_FILES',
    RECEIVE_FILES_BY_DEPARTMENT: 'RECEIVE_FILES_BY_DEPARTMENT',
    RECEIVE_FILE_BY_ID: 'RECEIVE_FILE_BY_ID',
    RECEIVE_FILE_BY_NO: 'RECEIVE_FILE_BY_NO',
    RECEIVE_AUTHENTICATED_USER: 'RECEIVE_AUTHENTICATED_USER',
    RECEIVE_ERROR: 'RECEIVE_ERROR',
    RECEIVE_SUCCESS: 'RECEIVE_SUCCESS',
    ADD_FILE_NOTE: 'ADD_FILE_NOTE',
    ADD_FILE_MOVEMENT: 'ADD_FILE_MOVEMENT',
    RECIEVE_FILE_NOTE_FOR_FILE: 'RECIEVE_FILE_NOTE_FOR_FILE',
    RECEIVE_FILE_MOVEMENT_FOR_FILE: 'RECEIVE_FILE_MOVEMENT_FOR_FILE',
    SEARCH_FILE: 'SEARCH_FILE',
    SELECT_FILE: 'SELECT_FILE',
    SELECT_USER: 'SELECT_USER',
    SELECT_DEPARTMENT: 'SELECT_DEPARTMENT'
};

export default types;